import re
from typing import Callable

def generator_numbers(text: str):
    """
    The function is used for generating numbers from the text.
    """
    #Create a pattern for finding all even numbers
    pattern = r"[-+]?\d*\.\d+|[-+]?\d+"
    #Find all matches of the pattern in the text and store them in the list
    matches = re.findall(pattern, text)
    #Iterate all matches and convert them to float
    for match in matches:
        yield float(match)

def sum_profit(text: str, func: Callable):
    """
    The function is used for calculating the total profit from the text.
    """
    #Calculate the total profit by summing all numbers from the text, numbers are generated by the func
    total = sum(func(text))
    return total

text = "Загальний дохід працівника складається з декількох частин: 1000.01 як основний дохід, доповнений додатковими надходженнями 27.45 і 324.00 доларів."
total_income = sum_profit(text, generator_numbers)
print(f"Загальний дохід: {total_income}")

